### PR TITLE
Update OpenWRT instructions in readme-vars.yml

### PR DESCRIPTION
**Pull request by dezeroku**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-netbootxyz/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Update the OpenWRT setup instructions, so not only the last dhcp-boot/dhcp-match pair is applied.

## Benefits of this PR and context:

Resolves https://github.com/linuxserver/docker-netbootxyz/issues/62

## How Has This Been Tested?

Works fine in my OpenWRT setup, booting from a VM and a "physical" device.

### CODE REVIEW

**Review by thelamer — APPROVED** [review]

**Comment by drizuid** [comment]
if we're not going to use uci, may as well delete the section and list wrt along with the other dnsmasq section since it's just a repeat

**Comment by dezeroku** [comment]
Good call, I'll change it.

Do you think it's a good idea to add a pointer that dnsmasq service likely needs to be restarted for the changes to take effect? I'd expect this to be true for most systems, not only OpenWRT

**Comment by drizuid** [comment]
> Good call, I'll change it.
> 
> Do you think it's a good idea to add a pointer that dnsmasq service likely needs to be restarted for the changes to take effect? I'd expect this to be true for most systems, not only OpenWRT

yes, the restart is definitely a good call and will complement the section nicely

**Review by drizuid — CHANGES_REQUESTED** [review]
you were going to keep the note regarding dnsmasq restart, right?  I would not put /etc/init.d/dnsmasq restart, but rather something along the lines of "Ensure you restart your DNSMASQ service after the changes."

**Review by drizuid — APPROVED** [review]

**Pull request merged**
